default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: protospace_テックマスターのuser_id5_development


test:
  <<: *default
  database: protospace_テックマスターのuser_id5_test


production:
  <<: *default
  database: protospace_テックマスターのuser_id5_production
  username: protospace_テックマスターのuser_id5
  password: <%= ENV["PROTOSPACE_テックマスターのUSER_ID5_DATABASE_PASSWORD"] %>