default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: protospace-40764_development


test:
  <<: *default
  database: protospace-40764_test


production:
  <<: *default
  database: protospace-40764_production
  username: protospace-40764
  password: <%= ENV["PROTOSPACE-40764_DATABASE_PASSWORD"] %>